<img src="http://cfs22.simplicdn.net/ice9/new_logo.svgz "/>

# Assignment 01: Evaluate the Ad Budget Dataset of XYZ Firm

*The comments/sections provided are your cues to perform the assignment. You don't need to limit yourself to the number of rows/cells provided. You can add additional rows in each section to add more lines of code.*

*If at any point in time you need help on solving this assignment, view our demo video to understand the different steps of the code.*

**Happy coding!**

* * *

#### 1: Import the dataset

In [119]:
#Import the required libraries
import numpy as np
import pandas as pd

In [120]:
#Import the advertising dataset
data = pd.read_csv("Advertising Budget and Sales.csv",index_col=0)

#### 2: Analyze the dataset

In [121]:
#View the initial few records of the dataset
data.head()

TV Ad Budget ($)  Radio Ad Budget ($)  Newspaper Ad Budget ($)  Sales ($)
1             230.1                 37.8                     69.2       22.1
2              44.5                 39.3                     45.1       10.4
3              17.2                 45.9                     69.3        9.3
4             151.5                 41.3                     58.5       18.5
5             180.8                 10.8                     58.4       12.9

In [122]:
#Check the total number of elements in the dataset
data.size

800

In [123]:
data.shape

(200, 4)

#### 3: Find the features or media channels used by the firm

In [124]:
#Check the number of observations (rows) and attributes (columns) in the dataset
data.values

array([[230.1,  37.8,  69.2,  22.1],
       [ 44.5,  39.3,  45.1,  10.4],
       [ 17.2,  45.9,  69.3,   9.3],
       [151.5,  41.3,  58.5,  18.5],
       [180.8,  10.8,  58.4,  12.9],
       [  8.7,  48.9,  75. ,   7.2],
       [ 57.5,  32.8,  23.5,  11.8],
       [120.2,  19.6,  11.6,  13.2],
       [  8.6,   2.1,   1. ,   4.8],
       [199.8,   2.6,  21.2,  10.6],
       [ 66.1,   5.8,  24.2,   8.6],
       [214.7,  24. ,   4. ,  17.4],
       [ 23.8,  35.1,  65.9,   9.2],
       [ 97.5,   7.6,   7.2,   9.7],
       [204.1,  32.9,  46. ,  19. ],
       [195.4,  47.7,  52.9,  22.4],
       [ 67.8,  36.6, 114. ,  12.5],
       [281.4,  39.6,  55.8,  24.4],
       [ 69.2,  20.5,  18.3,  11.3],
       [147.3,  23.9,  19.1,  14.6],
       [218.4,  27.7,  53.4,  18. ],
       [237.4,   5.1,  23.5,  12.5],
       [ 13.2,  15.9,  49.6,   5.6],
       [228.3,  16.9,  26.2,  15.5],
       [ 62.3,  12.6,  18.3,   9.7],
       [262.9,   3.5,  19.5,  12. ],
       [142.9,  29.3,  12.6,  15. ],
 

In [125]:
#View the names of each of the attributes
data.columns

Index(['TV Ad Budget ($)', 'Radio Ad Budget ($)', 'Newspaper Ad Budget ($)',
       'Sales ($)'],
      dtype='object')

# 1. Problem Statement 1 is solved.
## There are 3 Features are Media channel's Used by the firm.
1. TV
2. Radio
3. Newspaper

#### 4: Create objects to train and test the model; find the sales figures for each channel

In [94]:
#Create a feature object from the columns
feature_data = data.iloc[:,0:3]

In [95]:
#View the feature object
feature_data

TV Ad Budget ($)  Radio Ad Budget ($)  Newspaper Ad Budget ($)
1               230.1                 37.8                     69.2
2                44.5                 39.3                     45.1
3                17.2                 45.9                     69.3
4               151.5                 41.3                     58.5
5               180.8                 10.8                     58.4
..                ...                  ...                      ...
196              38.2                  3.7                     13.8
197              94.2                  4.9                      8.1
198             177.0                  9.3                      6.4
199             283.6                 42.0                     66.2
200             232.1                  8.6                      8.7

[200 rows x 3 columns]

# 2. Problem Statement 2 is solved:
## Sales figures for each channel is represented by feature_data in the above dataframe

In [127]:
#Create a target object (Hint: use the sales column as it is the response of the dataset)
response_data = data['Sales ($)']

In [128]:
#View the target object
print(response_data)
type(response_data)

1      22.1
2      10.4
3       9.3
4      18.5
5      12.9
       ... 
196     7.6
197     9.7
198    12.8
199    25.5
200    13.4
Name: Sales ($), Length: 200, dtype: float64


pandas.core.series.Series

In [129]:
#Verify if all the observations have been captured in the feature object
print(feature_data.shape)

(200, 3)


In [130]:
#Verify if all the observations have been captured in the target object
print(response_data.shape)

(200,)


In [131]:
X = feature_data
Y = response_data

## 3. Problem statement 4th is solved by spiliting the datasets
#### 5: Split the original dataset into training and testing datasets for the model

In [133]:
#Split the dataset (by default, 75% is the training data and 25% is the testing data)
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.25, random_state=1)

In [134]:
#Verify if the training and testing datasets are split correctly (Hint: use the shape() method)
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(150, 3)
(150,)
(50, 3)
(50,)


## 4. Problem statement 3rd is solved to create a model.
#### 6: Create a model  to predict the sales outcome

In [103]:
#Create a linear regression model
from sklearn.linear_model import LinearRegression
Mymodel = LinearRegression()
Mymodel.fit(X_train, Y_train)

LinearRegression()

In [104]:
#Print the intercept and coefficients 
print(Mymodel.intercept_)
print(Mymodel.coef_)

2.8769666223179318
[0.04656457 0.17915812 0.00345046]


In [106]:
#Predict the outcome for the testing dataset
Y_pred = Mymodel.predict(X_test)

In [107]:
Y_pred

array([21.70910292, 16.41055243,  7.60955058, 17.80769552, 18.6146359 ,
       23.83573998, 16.32488681, 13.43225536,  9.17173403, 17.333853  ,
       14.44479482,  9.83511973, 17.18797614, 16.73086831, 15.05529391,
       15.61434433, 12.42541574, 17.17716376, 11.08827566, 18.00537501,
        9.28438889, 12.98458458,  8.79950614, 10.42382499, 11.3846456 ,
       14.98082512,  9.78853268, 19.39643187, 18.18099936, 17.12807566,
       21.54670213, 14.69809481, 16.24641438, 12.32114579, 19.92422501,
       15.32498602, 13.88726522, 10.03162255, 20.93105915,  7.44936831,
        3.64695761,  7.22020178,  5.9962782 , 18.43381853,  8.39408045,
       14.08371047, 15.02195699, 20.35836418, 20.57036347, 19.60636679])

## 5. Problem Statement 5th is solved by calculating MSE.
#### 7: Calculate the Mean Square Error (MSE)

In [135]:
#Import required libraries for calculating MSE (mean square error)
from sklearn.metrics import mean_squared_error

In [136]:
#Calculate the MSE
mse = mean_squared_error(Y_test, Y_pred)
print("mean square error is :  ", mse)

mean square error is :   1.9730456202283368


In [137]:
# Root mean Squared Error:
from sklearn import metrics
print(np.sqrt(metrics.mean_squared_error(Y_test,Y_pred)))

1.404651423032895
